### ISSUE TITLE
Not accessible on browser

### ISSUE THREAD

**Issue by suarkadipa** [btwardow/tf-face-recognition#1]
after type -> docker run -it --rm -p 5000:5000 btwardow/tf-face-recognition:1.0.0

it logs
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-06-29 02:22:07.981537: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Model filename: /root/pretrained_models/20180402-114759/20180402-114759.pb
 * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)

but tried to access it based on top log to https://0.0.0.0:5000/, is not accessible, tried on https://localhost:5000/ is not accessible as well

I'm running on windows 10
Python 3.6.2
TensorFlow 1.8.0

Thank you

**Comment by btwardow** [comment]
Hi,

The version of the python and TF on your host machine doesn't matter, as everything run from the docker container. That's the main point of dockerization - make it easily reproducible. 

From the logs it seems that the application is initialized and run correctly.

I would investigate if the port 5000 from the container is properly bind to host machine. You can try few things:
 - change port mapping parameter to -p 0.0.0.0:5000:5000
 - try also https://127.0.0.1:5000

Sorry, but I don't know details of network interfaces for win10. Have you had similar problems with different containers before?

**Comment by btwardow** [comment]
Ping @suarkadipa 
Does it solved your problem?
