### ISSUE TITLE
Can we change the face recognition algorithm ?

### ISSUE THREAD

**Issue by jainhemendrah** [btwardow/tf-face-recognition#3]
Dear btwardow,
   Can we change the face recognition algorithm ? 
Example,  Google’s pre-trained Inception Convolutional Neural Network to perform image recognition .

If Yes, please suggest what modification we can have to do ?

Also, the application is great, but a bit slower in recognition. Can,  we improve the speed of recognition ?

**Comment by btwardow** [comment]
Hi @jainhemendrah, 

good question. Sure you can use any algorithm. 
In my proposed solution, the image is embedded using pre-trained net `VGGFace2` then kNN. 

What can I suggest is only to use not generic pre-trained network, but a one pre-trained for faces. 

Hope you will find this repo still useful for your needs.

**Comment by jainhemendrah** [comment]
Thanks btwardow.
>>What can I suggest is only to use not generic pre-trained network, but a one pre-trained for faces.
[JAIN] Sure.
Also,
I checked out "recognition.py"
result = classifier.predict(X)
..........
How can I change the classifier.predict() to use Inception_V2 model for Face Recognition. Can you help me modify "classifier.py" to use Inception_V2
