### ISSUE TITLE
Detection is too slow

### ISSUE THREAD

**Issue by sumit1212** [btwardow/tf-face-recognition#8]
* Detection is too slow. 
* Detect only one face at a time.
* When click the capture button it capture the images in too slow.
how to increase the capturing speed.

Please give me help for 3 points.
what can I do to solve these issues.

**Comment by btwardow** [comment]
The detection time is highly dependent on your project setup on which you are running the project - hardware (CPU/GPU), network between server and the client, and what is the size of your video: 
https://github.com/btwardow/tf-face-recognition/blob/master/server/static/local.js#L7-L9

The capturing has also quite few parameters. All is happening here: 
https://github.com/btwardow/tf-face-recognition/blob/master/server/static/detect.js
where you can play around with some parameters. 

Only one thing to notice here is that if you grab all the examples really fast, there's a risk they will be too similar. This can influence the recognition performance as well as the number of taken examples.

**Comment by sumit1212** [comment]
Thank you for your response.

>

**Comment by sumit1212** [comment]
What would be apply to detect face fast and moving detection with faces.

Thanks
